<?php

/**
 * @file
 * Functions to support theming in the SiteFarm One subtheme.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function sf1subtheme_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Change the title of a field on the Events Filter.
  if ($form_id == 'views_exposed_form' && $form["#id"] == 'views-exposed-form-sf-events-listing-page-1') {
    $form["#info"]["filter-title"]["label"] = 'Event Title';
  }
}
